name: clippy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  rust-clippy-analyze:
    name: analyze
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.68.2
          components: clippy
      
      - name: Setup cargo-binstall
        run: |
          wget -q -O binstall.tgz https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz
          tar xf binstall.tgz
          mv cargo-binstall $HOME/.cargo/bin/
          rm -f binstall.tgz

      - name: Install required cargo
        run: cargo binstall --no-confirm clippy-sarif sarif-fmt

      - name: Run rust-clippy
        run:
          cargo clippy
          --all-features
          --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true