on:
  pull_request:
    branches: [ master ]
    
env:
  CARGO_INCREMENTAL: 0

name: test
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [1.68.2, stable]
    steps:
      - uses: actions/checkout@v3

      - id: toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          targets: ${{ matrix.target }}
          components: rustfmt

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
      
      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Build tests
        run: cargo test --no-run

      - name: Test
        run: cargo test