on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
    
env:
  CARGO_INCREMENTAL: 0

name: test
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [1.68.2, stable]
    container:
      image: xd009642/tarpaulin:latest
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v3

      - id: toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          targets: ${{ matrix.target }}
          components: rustfmt

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
      
      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Test
        run: cargo tarpaulin --out Xml

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true